# This workflow runs every Saturday @ 1900 UTC (NOON PST)
name: i18n download bot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * 6"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DIM
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Download updated i18n files
        uses: crowdin/github-action@1.0.4
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          create_pull_request: false
          push_translations: false
          source: src/locale/dim.json
          translation: src/locale/%android_code%/dim.json
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: sort dim.json
        run: jq -S . src/locale/dim.json > src/locale/dim_sorted.json && mv src/locale/dim_sorted.json src/locale/dim.json

      - name: sort locale dim.json
        run: |
          allLocales=("de" "es" "es-mx" "fr" "it" "ja" "ko" "pl" "pt-br" "ru" "zh-chs" "zh-cht")
          for lang in ${allLocales[@]}; do
            jq -S . src/locale/$lang/dim.json > src/locale/$lang/dim_sorted.json && mv src/locale/$lang/dim_sorted.json src/locale/$lang/dim.json
          done

      - name: Check for new files (DIM)
        id: porcelain
        run: echo ::set-output name=porcelain::"$(git status --porcelain)"

#      - name: Create Pull Request (DIM)
#        if: steps.porcelain.outputs.porcelain
#        uses: peter-evans/create-pull-request@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          commit-message: i18n - ${{ env.GITHUB_SHA_SHORT }}
#          committer: DIM i18n Bot <destinyitemmanager@gmail.com>
#          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
#          title: '[i18n] Updates'
#          body: i18n updates
#          labels: i18n, automated pr
#          reviewers: delphiactual
#          branch: i18n

      - name: Commit files
        if: steps.porcelain.outputs.porcelain
        run: |
          git config --local user.email "destinyitemmanager@gmail.com"
          git config --local user.name "DIM i18n Bot"
          git commit -m "i18n - ${{ env.GITHUB_SHA_SHORT }}" -a

      - name: Push changes
        if: steps.porcelain.outputs.porcelain
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.I18N_PAT }}
